name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          toolchain: stable
          target: x86_64-unknown-uefi
          override: true
    - name: Build
      run: cargo build --verbose --target x86_64-unknown-uefi
